### ISSUE TITLE
FileNotFoundException when calling put(String local,String remote) in latest update

### ISSUE THREAD

**Issue by psezwar** [sshtools/maverick-synergy#1] opened 2020-04-08 09:48 UTC
I am getting FileNotFound Exception in put(String local,String remote) method when using the below dependency in maven file.
		<dependency>
			<groupId>com.sshtools</groupId>
			<artifactId>maverick-synergy-client</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
and the code snippet as below
ssh.runTask(new SftpClientTask(ssh) {
			@Override
			protected void doSftp() {
				try {
					log.info("File to Copy:{}", fileToCopy.getAbsolutePath());
					put(fileToCopy.getAbsolutePath(), remoteDir);
					log.info("SFTP File put operation done successfully");
					isSftpSuccessful = Boolean.TRUE;
				} catch (FileNotFoundException e) {
					e.printStackTrace();
					message = "Seems invalid file is being uploaded through SFTP";
					isSftpSuccessful = Boolean.FALSE;
				} catch (SftpStatusException e) {
					e.printStackTrace();
					if (e.getStatus() == SftpStatusException.SSH_FX_PERMISSION_DENIED) {
						message = "Failed to create file in remote directory as the configured user don't have permission to create one";
					}
					isSftpSuccessful = Boolean.FALSE;
				} catch (SshException e) {
					e.printStackTrace();
					isSftpSuccessful = Boolean.FALSE;
				} catch (TransferCancelledException e) {
					e.printStackTrace();
					isSftpSuccessful = Boolean.FALSE;
				} catch (Exception e) {
					e.printStackTrace();
					isSftpSuccessful = Boolean.FALSE;
				}
			}
		});
		
This was working fine 1 week back when I had the maverick-synergy-client-3.0.0-20200225.155328-75.jar in my .m2 repository.
After I build my code again yesterday,I got some new dependencies downloaded in my .m2 repo and the maverick-synergy-client-3.0.0-20200405.143821-96.jar.Since then I an getting below exception 

File to Copy:C:\Users\PSEZWAR\WelcomeSFTP.txt
java.io.FileNotFoundException: C:\Users\PSEZWAR\C:\Users\PSEZWAR\WelcomeSFTP.txt (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.sshtools.common.files.direct.AbstractDirectFile.getInputStream(AbstractDirectFile.java:109)
	at com.sshtools.client.sftp.SftpClient.put(SftpClient.java:1778)
	at com.sshtools.client.sftp.SftpClient.put(SftpClient.java:1892)
	at com.sshtools.client.sftp.SftpClientTask.put(SftpClientTask.java:976)
	at com.xylem.owareportservice.util.SFTPUtil$1.doSftp(SFTPUtil.java:129)
	at com.sshtools.client.sftp.SftpClientTask.doTask(SftpClientTask.java:55)
	at com.sshtools.common.ssh.ConnectionAwareTask.run(ConnectionAwareTask.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I have my local file at C:\Users\PSEZWAR\WelcomeSFTP.txt but the code is appending the C:\Users\PSEZWAR\ to my file location resulting the FileNotFoundException.
Please look into this issue as this was not existing in previous revision.Please help me to resolve the issue.

**Comment by ludup** [comment] 2020-04-17 12:39
Thanks for the feedback.

SftpClient and SftpClientTask changed recently to use our AbstractFile implementations as the local file system. The problem was caused by the DirectFile implementation not handling the absolute path correctly as you pointed out. 

The benefit of upgrading to use AbstractFile is you can now use any type of file system as the local file system, for example using VFSFileFactory, you could use any of the file systems supported by Commons VFS as the local system.

New SNAPSHOT should be building shortly.

**Comment by psezwar** [comment] 2020-04-18 06:02
Thank Ludup for the explanation.
Hopefully the new SNAPSHOT solves the problem.

**Comment by ludup** [comment] 2020-04-23 12:45
How did you get on with the new SNAPSHOT?

**Comment by ludup** [comment] 2020-06-12 12:15
Closing, it was fixed. User did not confirm.

**Closed by ludup** 2020-06-12 12:15 UTC
